### ISSUE TITLE
Per-project installation does not work on desktop

### ISSUE THREAD

**Issue by SushiTee** [lirios/fluid#169]
I'm planning to wite an app which runs on both android and desktop. So I tried "minimalqmake". I cloned fluid into it and tried to start it on desktop.

I'm working on windows.

```
qrc:/main.qml:5 module "Fluid.Effects" is not installed
qrc:/main.qml:4 module "Fluid.Controls" is not installed
qrc:/main.qml:5 module "Fluid.Effects" is not installed
qrc:/main.qml:4 module "Fluid.Controls" is not installed
```

**Comment by rmallah** [comment]
There is discussion about it here:
https://github.com/lirios/fluid/issues/103

maybe the old issue can be re-opened if required,

**Comment by SushiTee** [comment]
The other issue was about Qt Creator. Qt creator does resolve the types.

**Comment by rmallah** [comment]
Hi SushiTee , 

I replicated the problem in linux . a modification to main.cpp and src.pro as per
https://github.com/rmallah/fluid/commit/931ab34f650a4c98714d91698c54e7af97eb42d3
provides a running example . Can you please test it in windows / your environment .

**Comment by rmallah** [comment]
pls consider this  

https://github.com/rmallah/fluid/commit/9205b8281031ab921ca41b18e5780719702123b3

instead.

**Comment by SushiTee** [comment]
It seems to work. 👍

**Comment by plfiorini** [comment]
f070eb79ac62e983b7f1e6d44d4c3d52e2ac5f7f should fix it can you confirm @SushiTee and @rmallah ?

**Comment by rmallah** [comment]
Hi Pier , 
I was trying to test it.

I have Qt 5.9.2  , looks like some versions have been bumped up in TabbedPage
`module "QtQuick" version 2.10 is not installed`

even after temporarily downgrading the modules , the is a problem 
of availability of IconLabel.
regds
mallah

**Comment by plfiorini** [comment]
Yes Fluid 1.0 (which is what the `develop` branch is becoming( needs Qt 5.10 because it introduces the icon grouped property and I can't implement it afterwards since it is an incompatible change and the API should not break after Fluid 1.0

**Comment by rmallah** [comment]
Thanks Pier , 
Pls allow sometime for confirmation . As i have to download and install 5.10 . I was in middle of 
something.

regds
mallah.

**Comment by plfiorini** [comment]
@rmallah In order to check if it works you can just do the following changes to your project, no need to update Fluid, just stick with the `master` branch if you are using Qt 5.9.2:

https://github.com/lirios/fluid/commit/f070eb79ac62e983b7f1e6d44d4c3d52e2ac5f7f
https://github.com/lirios/fluid/commit/119701bce2bf044021fdeff892d04e92e8d95f07

**Comment by rmallah** [comment]
Hi Pier , 

there is no problem in loading the QML fluid modules.
however the imageproviders  seems to be having problem

```
file:///mnt/khajana/Qt/Projects/NG/testfluid/fluid/examples/perproject/build-minimalqmake-Desktop_Qt_5_9_2_GCC_64bit-Debug/fluid/qml/Fluid/Controls/Icon.qml:165:5: QML Image: Failed to get image from provider: image://fluidicons/navigation/arrow_back
```

**Comment by rmallah** [comment]
as asked by you i checked using the fluid master .

**Comment by SushiTee** [comment]
When I try to run the desktop build it still get the same errors about not finding the modules.

After I added another _QDir::separator() + QLatin1String("..")_ in the main.cpp it worked.

The UWP Build does not work because the fluid stuff is not copied into the directory with the final application executable.

**Comment by plfiorini** [comment]
@SushiTee Deployment is a separate issue, you should add the import path according to the deployment.

**Comment by plfiorini** [comment]
@SushiTee See http://doc.qt.io/qt-5/windows-deployment.html#the-windows-deployment-tool

**Comment by plfiorini** [comment]
@SushiTee This might do the trick but I haven't tested it yet, Windows is on another machine and I don't have VMs here: https://github.com/lirios/fluid/commit/3cf596ab4968373ed4e4a4618488365e95c8a538

**Comment by SushiTee** [comment]
I tried with your change. Whatever option I add to _WINDEPLOYQT_OPTIONS_ qtcreator is just ignoring it and always runs the same _windeployqt_ command. So I added a custom build step in qt creator:

```
command: windeployqt.exe
arguments: %{CurrentRun:Executable:FilePath} --qmldir %{CurrentProject:Path} --qmldir %{buildDir}\fluid\qml\Fluid
workingdir: %{buildDir}
```
After this the intended deply setp was done. All it does is scan for imports in the fluid directory. It doesn't copy anything.
There seems to be no option to deploy additional plugins with _windeployqt_.

There seems to be a related qt bug: https://bugreports.qt.io/browse/QTBUG-43472

**Comment by plfiorini** [comment]
Closing, it should work now setting the import path

**Comment by magnus-gross** [comment]
Still not working for me.
Maybe I could solve my error, if the minimalqmake would work.
When I go to `fluid/examples/perproject/minimalqmake` and execute `ln -s ../../.. fluid` to create the required fluid subfolder and after that execute the usual build pipeline, I get an error.
```
mkdir build
cd build
qmake ..
make
```
The error is: ` rule to make target '/home/magnus/Documents/Qt/fluid/src/imports/core/qmldateutils.cpp', needed by '.obj/qmldateutils.o'.  Stop.`

**Comment by plfiorini** [comment]
@magnus-gross .pro file were not updated try now

**Comment by magnus-gross** [comment]
Thanks, works now

**Comment by plfiorini** [comment]
You are welcome. I often forget to update .pro files but I use a glob now so hopefully it won't break when files are moved.

**Comment by magnus-gross** [comment]
Just tried it out in Windows. Even the minimalqmake from fluid doesn't work there. You get the usual "Fluid.Effects" is not installed error messages. Don't know what is the issue, because it is working perfectly fine on Linux.
